[2024-01-19T04:39:23.485+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: company_profile_pipeline.CheckTableExisting manual__2024-01-19T04:39:22.547662+00:00 [queued]>
[2024-01-19T04:39:23.491+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: company_profile_pipeline.CheckTableExisting manual__2024-01-19T04:39:22.547662+00:00 [queued]>
[2024-01-19T04:39:23.492+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-01-19T04:39:23.507+0000] {taskinstance.py:2192} INFO - Executing <Task(BranchPythonOperator): CheckTableExisting> on 2024-01-19 04:39:22.547662+00:00
[2024-01-19T04:39:23.515+0000] {standard_task_runner.py:60} INFO - Started process 200 to run task
[2024-01-19T04:39:23.520+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'company_profile_pipeline', 'CheckTableExisting', 'manual__2024-01-19T04:39:22.547662+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/CrawlCompanyInfo.py', '--cfg-path', '/tmp/tmpivh7_1oc']
[2024-01-19T04:39:23.521+0000] {standard_task_runner.py:88} INFO - Job 4: Subtask CheckTableExisting
[2024-01-19T04:39:23.558+0000] {task_command.py:423} INFO - Running <TaskInstance: company_profile_pipeline.CheckTableExisting manual__2024-01-19T04:39:22.547662+00:00 [running]> on host ae6c997f1cf2
[2024-01-19T04:39:23.624+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='anh.ho@tititada.com' AIRFLOW_CTX_DAG_OWNER='anh.ho' AIRFLOW_CTX_DAG_ID='company_profile_pipeline' AIRFLOW_CTX_TASK_ID='CheckTableExisting' AIRFLOW_CTX_EXECUTION_DATE='2024-01-19T04:39:22.547662+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-19T04:39:22.547662+00:00'
[2024-01-19T04:39:23.626+0000] {logging_mixin.py:188} INFO - Connecting to the PostgreSQL database...
[2024-01-19T04:39:23.629+0000] {logging_mixin.py:188} INFO - PostgreSQL database version:
[2024-01-19T04:39:23.630+0000] {logging_mixin.py:188} INFO - Successfully connect to Postgresql
[2024-01-19T04:39:23.630+0000] {logging_mixin.py:188} INFO - ('PostgreSQL 13.13 (Debian 13.13-1.pgdg120+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit',)
[2024-01-19T04:39:23.630+0000] {logging_mixin.py:188} INFO - Checking existing table...
[2024-01-19T04:39:23.633+0000] {python.py:201} INFO - Done. Returned value was: CreateCompanyProfileTable
[2024-01-19T04:39:23.633+0000] {branch.py:35} INFO - Branch into CreateCompanyProfileTable
[2024-01-19T04:39:23.634+0000] {skipmixin.py:178} INFO - Following branch CreateCompanyProfileTable
[2024-01-19T04:39:23.647+0000] {skipmixin.py:244} INFO - Skipping tasks [('ExistingCompanyProfile', -1)]
[2024-01-19T04:39:23.685+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=company_profile_pipeline, task_id=CheckTableExisting, execution_date=20240119T043922, start_date=20240119T043923, end_date=20240119T043923
[2024-01-19T04:39:23.736+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-19T04:39:23.759+0000] {taskinstance.py:3281} INFO - 1 downstream tasks scheduled from follow-on schedule check
